import { describe,it,expect } from "vitest";
import { buildIllustratedScene, exportGlb, validateIllustration, type Illustration } from "../lib/local/scene";
import { validatePlanIds, truncateUtf8 } from "../lib/local/pipeline";
import { type TutorialPlan } from "../lib/contracts";
const plan:TutorialPlan={version:1,title:"Move a cup",goal:"Place the cup under the spout",description:"An illustrated test",category:"coffee",difficulty:"Beginner",estimatedMinutes:1,objects:[{id:"cup",name:"Cup",kind:"vessel",observed:true,notes:""}],steps:[{id:"place",title:"Place the cup",instruction:"Move the cup to the spout",narration:"Place your cup under the spout.",durationSeconds:5,objectIds:["cup"],observable:true,completionCriteria:"Cup is under the spout",sourceIds:[],action:"move"}],sources:[],questions:[],constraints:[]};
const illustration:Illustration={surface:{width:1,depth:.6,color:"#dfd8c8"},objects:[{id:"cup",position:{x:0,y:0,z:0},movable:true,parts:[{shape:"cylinder",position:{x:0,y:.05,z:0},size:{x:.09,y:.1,z:.09},rotation:{x:0,y:0,z:0},color:"#f2eee4",metallic:false}]}],gestures:[{stepId:"place",objectId:"cup",hand:"right",contact:{x:0,y:.08,z:0},endPosition:{x:.2,y:0,z:.1},endRotation:null}],uncertainty:["Approximate dimensions"]};
describe("Local illustrated scene",()=>{
  it("exports a real portable GLB with baked human-hand and object animation",async()=>{const built=buildIllustratedScene(plan,illustration);const bytes=await exportGlb(built.scene,built.clip);expect(bytes.subarray(0,4).toString()).toBe("glTF");expect(bytes.length).toBeLessThan(20_000_000);const jsonLength=bytes.readUInt32LE(12);const gltf=JSON.parse(bytes.subarray(20,20+jsonLength).toString());expect(gltf.animations).toHaveLength(1);expect(gltf.nodes.some((n:{name:string})=>n.name==="TutorHand_R")).toBe(true);expect(built.manifest.mode).toBe("illustrated");expect(built.manifest.landmarks).toEqual([]);expect(built.manifest.quality.registeredFrameRatio).toBe(0);const position=built.clip.tracks.find(t=>t.name==="Object_cup.position")!;expect(Array.from(position.values.slice(-3))).toEqual([expect.closeTo(.2,4),0,expect.closeTo(.1,4)]);});
  it("rejects unknown references, duplicated steps and attempts to move fixed equipment",()=>{expect(()=>validateIllustration(plan,{...illustration,gestures:[{...illustration.gestures[0],objectId:"unknown"}]})).toThrow();expect(()=>validateIllustration(plan,{...illustration,gestures:[...illustration.gestures,...illustration.gestures]})).toThrow();expect(()=>validateIllustration(plan,{...illustration,objects:[{...illustration.objects[0],movable:false}]})).toThrow();});
  it("bounds geometry and preserves a matching step timebase",()=>{expect(()=>validateIllustration(plan,{...illustration,objects:[{...illustration.objects[0],position:{x:200,y:0,z:0}}]})).toThrow();const built=buildIllustratedScene(plan,illustration,{place:9});expect(built.clip.duration).toBe(9);expect(built.manifest.steps[0].endTime).toBe(9);expect(built.manifest.durationSeconds).toBe(9);});
  it("validates plan identity and limits UTF-8 narration inputs",()=>{expect(()=>validatePlanIds({...plan,steps:[{...plan.steps[0],objectIds:["absent"]}]})).toThrow();const result=truncateUtf8("☕".repeat(100),40);expect(Buffer.byteLength(result)).toBeLessThanOrEqual(40);expect(result).not.toContain("�");});
});
