import type { Tutorial, TutorialPlan, TutorialStep } from "./contracts";
const date = "2026-09-10T12:00:00.000Z";
function step(id: string, title: string, instruction: string, action: TutorialStep["action"], objectIds: string[], observable = true): TutorialStep {
  return { id, title, instruction, narration: instruction, action, objectIds, durationSeconds: 8, observable, completionCriteria: observable ? `The visible result of “${title}” is present.` : "Confirm this step yourself; a camera image cannot establish its result alone.", sourceIds: [] };
}
function example(id: string, slug: string, plan: TutorialPlan, image: string): Tutorial {
  return { id, ownerId: "astratorial-examples", title: plan.title, slug, description: plan.description, category: plan.category, visibility: "public", status: "ready", revision: 1, createdAt: date, updatedAt: date, goal: plan.goal, constraints: plan.constraints, referenceUrls: [], assets: [], measurements: [], plan, scene: null, job: null, thumbnailUrl: image, isExample: true };
}
export const examples: Tutorial[] = [
  example("example-espresso", "your-everyday-espresso", {
    version: 1, title: "Your everyday espresso", goal: "Make a simple pod espresso with a splash of creamer.", description: "A better morning starts with one little ritual. Meet your machine, make your coffee, find your moment.", category: "coffee", difficulty: "Beginner", estimatedMinutes: 5,
    objects: [{ id: "machine", name: "Pod espresso machine", kind: "appliance", observed: false, notes: "Illustrative machine; controls and compatibility vary by model." }, { id: "cup", name: "Coffee cup", kind: "container", observed: false, notes: "Heat-safe cup." }, { id: "pod", name: "Coffee pod", kind: "ingredient", observed: false, notes: "Use a compatible pod." }, { id: "milk", name: "Creamer", kind: "ingredient", observed: false, notes: "Optional, to taste." }],
    steps: [step("espresso-1", "Get your machine ready", "Check your machine's instructions, fill its reservoir with fresh water, and turn it on. Wait for its ready indicator.", "point", ["machine"], false), step("espresso-2", "Pop in a coffee pod", "Open the pod compartment using the machine's handle. Insert a compatible pod in the direction shown on your machine, then close the compartment.", "insert", ["pod", "machine"]), step("espresso-3", "Make room for your cup", "Place a heat-safe cup on the drip tray beneath the coffee outlet.", "move", ["cup", "machine"]), step("espresso-4", "Let it brew", "Choose the espresso setting on your machine. Keep your hands clear of the hot outlet and wait for the flow to stop.", "press", ["machine", "cup"], false), step("espresso-5", "Make it yours", "Once brewing has stopped, carefully move your cup to the counter. Add a little creamer if you like, then give it a gentle stir.", "pour", ["milk", "cup"]), step("espresso-6", "A little reset", "When the machine has cooled, eject the used pod according to its instructions and wipe up any spills. Your coffee is ready.", "release", ["machine", "cup"], false)], sources: [], questions: [], constraints: ["Curated illustrative example, not a scan of your room.", "Follow the instructions for your exact machine; this example does not establish model-specific operation."],
  }, "/images/espresso.png"),
  example("example-cooking", "a-little-tomato-basil-magic", {
    version: 1, title: "A little tomato & basil magic", goal: "Make a simple tomato and basil pasta.", description: "A few good ingredients. A little time at the stove. Bring a fresh, comforting dinner together one step at a time.", category: "cooking", difficulty: "Beginner", estimatedMinutes: 20,
    objects: [{ id: "bowl", name: "Serving bowl", kind: "container", observed: false, notes: "Heat-safe bowl." }, { id: "pasta", name: "Pasta", kind: "ingredient", observed: false, notes: "Cook according to package directions." }, { id: "tomatoes", name: "Tomatoes", kind: "ingredient", observed: false, notes: "Washed and prepared before cooking." }, { id: "basil", name: "Fresh basil", kind: "ingredient", observed: false, notes: "Washed and ready to use." }],
    steps: [step("cooking-1", "Gather the good things", "Set out pasta, washed tomatoes, fresh basil, olive oil, and a serving bowl. Check ingredients for your dietary needs.", "point", ["bowl", "pasta", "tomatoes", "basil"]), step("cooking-2", "Let the pasta cook", "Cook the pasta in a suitable pot according to its package directions. Keep clear of steam and use heat protection around the hot pot.", "wait", ["pasta"], false), step("cooking-3", "Bring the tomatoes together", "Cook the prepared tomatoes gently in a pan with a little olive oil, stirring until they soften. Adjust the heat to avoid splattering.", "move", ["tomatoes"], false), step("cooking-4", "A happy little meeting", "Once the pasta is cooked, drain it carefully and add it to the tomatoes. Gently stir everything together.", "pour", ["pasta", "tomatoes"], false), step("cooking-5", "Make room for dinner", "Turn off the heat. Use a suitable utensil to transfer the pasta to your heat-safe serving bowl.", "move", ["pasta", "bowl"]), step("cooking-6", "The finishing touch", "Tear fresh basil over your pasta. Taste when cool enough, season to your preference, and enjoy.", "release", ["basil", "bowl"])], sources: [], questions: [], constraints: ["Curated illustrative example, not a scan of your kitchen.", "Follow pasta package instructions and your appliance's operating guidance."],
  }, "/images/cooking.png"),
  example("example-assembly", "a-side-table-made-by-you", {
    version: 1, title: "A side table, made by you", goal: "Understand the general process of assembling a small wooden side table.", description: "From a few simple pieces to a place for your favorites. See how it comes together, then make it happen.", category: "assembly", difficulty: "Beginner", estimatedMinutes: 25,
    objects: [{ id: "table", name: "Tabletop", kind: "furniture", observed: false, notes: "Illustrative flat-pack table; exact construction varies." }, { id: "legs", name: "Table legs", kind: "parts", observed: false, notes: "Match each leg to the supplied manual." }, { id: "screws", name: "Supplied fasteners", kind: "parts", observed: false, notes: "Use only the correct fasteners for your table." }, { id: "tool", name: "Assembly tool", kind: "tool", observed: false, notes: "Use the tool specified in the manufacturer manual." }],
    steps: [step("assembly-1", "Get to know the pieces", "Open the manufacturer's assembly instructions and identify the tabletop, legs, and supplied fasteners. Check that nothing is missing or damaged.", "point", ["table", "legs", "screws"]), step("assembly-2", "A soft place to start", "If your manual calls for upside-down assembly, place the tabletop face down on a clean, soft surface to protect its finish.", "rotate", ["table"]), step("assembly-3", "Find the first fit", "Identify the first leg and its mounting position in your manual. Align the leg and the specified fasteners without forcing the parts.", "move", ["legs", "table", "screws"]), step("assembly-4", "Bring the legs together", "Attach the legs in your manufacturer's sequence using its specified fasteners and tool. Follow its tightening guidance; do not improvise a torque value.", "rotate", ["legs", "screws", "tool"], false), step("assembly-5", "Stand it on its feet", "Once all connections are complete, turn the table upright carefully, with help if its size or weight calls for it.", "rotate", ["table"]), step("assembly-6", "The final little check", "Check for stability and confirm all connections against the manual. Follow the manufacturer's load limit and correct any wobble before using the table.", "point", ["table"], false)], sources: [], questions: [], constraints: ["Curated illustrative example, not a model-specific assembly manual or scan of your room.", "The supplied manufacturer instructions take precedence over this generic sequence."],
  }, "/images/assembly.png"),
];
export function getExample(id: string): Tutorial | undefined { return examples.find((tutorial) => tutorial.id === id || tutorial.slug === id); }
