"use client";
import Image from "next/image";
import Link from "next/link";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { errorMessage, post, useAppConfig } from "@/lib/client";
import { BrandMark, Icon } from "@/components/shell/icon";
export default function LoginPage() {
  const { config, loading, refresh } = useAppConfig();
  const [email, setEmail] = useState(""); const [token, setToken] = useState(""); const [sent, setSent] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null); const router = useRouter();
  async function send() { setBusy(true); setError(null); try { await post("/api/auth/otp", { email: email.trim() }); setSent(true); setNotice("Your sign-in code is on its way. Check your email, including your spam folder."); } catch (reason) { setError(errorMessage(reason)); } finally { setBusy(false); } }
  async function verify() { setBusy(true); setError(null); try { await post("/api/auth/verify", { email: email.trim(), token }); await refresh(); const next = new URLSearchParams(window.location.search).get("next"); let destination = "/library"; try { const target = next ? new URL(next, window.location.origin) : null; if (target?.origin === window.location.origin) destination = target.pathname + target.search + target.hash; } catch { /* Invalid return links open the library. */ } router.push(destination); } catch (reason) { setError(errorMessage(reason)); } finally { setBusy(false); } }
  return <div className="login-wrap"><div className="login-art"><Image src="/images/hero.png" alt="A quiet, sunlit kitchen ready for a new little ritual" fill sizes="(max-width: 950px) 90vw, 40vw" priority /><div className="login-art-copy"><h2>Good things<br />start at home.</h2><p>A space for everything you’re learning,<br />and everything you’re about to try.</p></div></div><div className="login-form"><BrandMark size={31} /><h1>{config?.user ? "You’re right at home." : sent ? "A little note in your inbox." : "A space for your possibilities."}</h1><p>{config?.user ? `You’re signed in as ${config.user.email}. Your next little victory is waiting.` : sent ? `Enter the code we sent to ${email}.` : "Sign in or create an account with your email. We’ll send you a code — no password to remember."}</p>{config?.user ? <Link href="/library" className="button button-primary">Go to my tutorials<Icon name="arrow" size={16} /></Link> : <><form onSubmit={(event) => { event.preventDefault(); if (sent) void verify(); else void send(); }}>{sent ? <label className="field">Your sign-in code<input className="otp-input" aria-label="Email sign-in code" inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6,10}" minLength={6} maxLength={10} required autoFocus value={token} onChange={(event) => setToken(event.target.value.replace(/\D/g, ""))} placeholder="000000" /></label> : <label className="field">Your email address<input type="email" autoComplete="email" required value={email} onChange={(event) => setEmail(event.target.value)} placeholder="you@home.com" /></label>}{error && <div className="notice notice-error" role="alert">{error}</div>}{notice && !error && <div className="notice notice-success" role="status">{notice}</div>}{!loading && !config?.services.database && <div className="notice"><Icon name="info" size={15} /><span>Accounts will be available once this workspace is connected. <Link href="/settings" style={{ textDecoration: "underline" }}>View setup</Link></span></div>}<button className="button button-primary" type="submit" disabled={busy || loading || !config?.services.database}>{busy ? <span className="spinner" /> : <Icon name={sent ? "arrow" : "mail"} size={16} />}{busy ? "One moment…" : sent ? "Make yourself at home" : "Send my sign-in code"}</button></form>{sent && <div className="button-row" style={{ marginTop: 12 }}><button className="button button-quiet button-small" style={{ width: "auto", flex: 1 }} disabled={busy} onClick={() => void send()}>Send a new code</button><button className="button button-quiet button-small" style={{ width: "auto", flex: 1 }} disabled={busy} onClick={() => { setSent(false); setToken(""); setNotice(null); setError(null); }}>Use another email</button></div>}<div className="login-note">Your captures are private. Your learning is yours.<br /><Link href="/explore">Just looking? Explore the examples.</Link></div></>}</div></div>;
}
